### ISSUE TITLE
error in server/main.lua 201

### ISSUE THREAD

**Issue by diepmiho** [deviljin112/rid_blackmarket#8]
Script ERROR: @rid_blackmarket/server/main.lua:201 attempt to index a nil value (global 'new_set')

I dont know if i've made a mistake when im trying to remove sa sniper categories because i dont want sniper in my server.

**Comment by nusikales** [comment]
same

**Comment by deviljin112** [comment]
When you removing a category remove it from the config only, you shouldnt have to change anything in the server files, as it only checks what is available in the config. Feel free to comment out line 208 -> 228 in the config file and dont forget to remove a comma on line 206. You also need to remove that weapon (sniper) from the DB if you imported it from the SQL file, as it will add it to your database and the menu will search only for weapons in the DB and then check what is set up in the config file. After making sure both config and DB doesnt contain a sniper you shouldn't see any issues.
